/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.Connection;
import java.sql.SQLException;

import org.example.persistence.config.ConnectionConfig;
import org.example.persistence.migration.MigrationStrategy;

public class Main {    
    public static void main(String[] args) throws SQLException{
        try(Connection connection = ConnectionConfig.getConnection()){
            new MigrationStrategy(connection).executeMigration();
        }
    }
}
